### ISSUE TITLE
Latest version will not open after restarting the computer

### ISSUE THREAD

**Issue by IamNooblike** [death7654/Chrultrabook-Tools#63] opened 2024-02-05 12:15 UTC
After installing the Chultrabook, it doesnt even opening once I restarted the computer (version 2.4.3+)

Previous version 2.4.1 doesn't have this issue. But on latest version of windows 11 (23H2) build, it will crash after a couple of hours / minutes.

**Comment by FEI352** [comment] 2024-02-06 08:45
Enabling the "Start App in System Tray" option in Settings causes the application to fail to open.

**Comment by IamNooblike** [comment] 2024-02-07 12:55
Even that option is turned off, the issue still persist.

**Comment by death7654** [comment] 2024-02-15 03:49
What chromebook, and can you post a video

**Comment by death7654** [comment] 2024-02-15 04:23
> Enabling the "Start App in System Tray" option in Settings causes the application to fail to open.

It will be in system tray

**Comment by janowakps** [comment] 2024-03-01 00:09
I can confirm that the "Start App On Boot" option does not work in the latest version and that the "Start App In System Tray" option causes the app to crash on startup and the only option to make the App work again is to uninstall with deletion of the app data and reinstall.

The problem occurs on sona chromebook with windows 11.

**Comment by daydreamingprince** [comment] 2024-03-08 16:24
> Enabling the "Start App in System Tray" option in Settings causes the application to fail to open.

Can confirm the problem exists in Drobit for quite some time now too.

A temporary workaround I did was to clean reinstall the app, then made sure to not enable the "Start app in system tray".

**Comment by death7654** [comment] 2024-03-08 16:26
I will work on diagnosing the issue this as soon as I find the time. Please give me all the information you can about this so we can publish a release as soon as possible. I do apologize for any inconveniences that we may have caused

**Comment by death7654** [comment] 2024-06-26 16:19
Please do use 2.8.1 as the issue is not present in these versions

**Closed by death7654** 2024-06-26 16:19 UTC
